package component.jtreecomponent;

import javax.swing.ImageIcon;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeNode;

/**
 *
 * @author MrDoisaac
 */
public class Window extends javax.swing.JFrame {
    
    // Creates a DefaultMutableTreeNode for our jTreeModel
    private DefaultMutableTreeNode root = new DefaultMutableTreeNode(new String("Root"));
    
    // Creates new model for the jTree
    private DefaultTreeModel jTreeModel = new DefaultTreeModel(root);
    
    public Window() {
        fillDataOfTreeModel();
        initComponents();
    }
    
    private void fillDataOfTreeModel(){
        // creates new node root "Colors" and add some colors nodes
        DefaultMutableTreeNode colors = new DefaultMutableTreeNode(new String("Colors"));
        DefaultMutableTreeNode redColor = new DefaultMutableTreeNode(new String("Red"));
        DefaultMutableTreeNode blueColor = new DefaultMutableTreeNode(new String("Blue"));
        colors.add(redColor);
        colors.add(blueColor);
        
        DefaultMutableTreeNode sports = new DefaultMutableTreeNode(new String("Sports"));
        DefaultMutableTreeNode footballsport = new DefaultMutableTreeNode(new String("Football"));
        // converting "footballsport into a root"
        DefaultMutableTreeNode indoorFootball = new DefaultMutableTreeNode(new String("Indoor football"));
        footballsport.add(indoorFootball);
        
        
        DefaultMutableTreeNode basketballsport = new DefaultMutableTreeNode(new String("Basketball"));
        sports.add(footballsport);
        sports.add(basketballsport);
        
        root.add(colors);
        root.add(sports);
    }
    
    /**
     * Shows a img references o what the user clicked
     */
    private void nodeSelectedEvent(DefaultMutableTreeNode node){
        if (node.toString().equals("Red")){
            imgLabel.setIcon(new ImageIcon(getClass().getResource("/img/red.png")));
        } 
        else if (node.toString().equals("Blue")){
            imgLabel.setIcon(new ImageIcon(getClass().getResource("/img/blue.png")));
        }
        else if (node.toString().equals("Indoor football")){
            imgLabel.setIcon(new ImageIcon(getClass().getResource("/img/football.png")));
        }
        else if (node.toString().equals("Basketball")){
            imgLabel.setIcon(new ImageIcon(getClass().getResource("/img/basket.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        imgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTree1.setModel(jTreeModel);

        TreeSelectionListener treeListener = new TreeSelectionListener(){
            @Override
            public void valueChanged(TreeSelectionEvent e){
                DefaultMutableTreeNode nodeSelected = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
                nodeSelectedEvent(nodeSelected);
            }
        };

        jTree1.getSelectionModel().addTreeSelectionListener(treeListener);

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
