/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doisaac.interfacedesigner;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MrDoisaac
 */
public class Window extends javax.swing.JFrame {
    
    private DefaultComboBoxModel<Person> personModel = new DefaultComboBoxModel<Person>();
    private DefaultTableModel tableModel = new DefaultTableModel();
    ArrayList<Person> peopleInTable = new ArrayList<>();
    
    /**
     * Creates new form Window
     */
    public Window() {
        fillPersonCombo();
        fillTableModel();
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /* Creates and fill the person model*/
    private void fillPersonCombo(){
        personModel.addElement(new Person("Douglas", "Barrera", "douglasb@gmail.com", "El Salvador, Santa Ana","+503 7050-6070" ));
        personModel.addElement(new Person("Carolina", "Magaña", "carolinam@gmail.com", "El Salvador, Santa Ana","+503 7151-6171" ));
        personModel.addElement(new Person("Josue", "Barrera", "josueb@gmail.com", "El Salvador, Santa Ana", "+503 7252-6272" ));
        personModel.addElement(new Person("Isabel", "Matias", "isabelb@gmail.com", "El Salvador, Santa Ana", "+503 7353-8393" ));
        personModel.addElement(new Person("Millie", "Brown", "milliebrown@gmail.com", "United States, LA", "+44 20 3868 0167"));
        personModel.addElement(new Person("Juan", "Guarnizo", "juanyoutube@gmail.com", "Mexico, Guadalajara","+52 141516 7888"));
        personModel.addElement(new Person("Alejandra", " Megan", "alejandranoticias@gmail.com", "El Salvador, San Salvador","+503 7855-9922"));
        
    }
    
    private void fillTableModel(){
        tableModel.addColumn("Name");
        tableModel.addColumn("Last Name");
        tableModel.addColumn("Email");
        tableModel.addColumn("Direction");
        tableModel.addColumn("Phone Number");
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        personLabel = new javax.swing.JLabel();
        personCombo = new javax.swing.JComboBox<>();
        insertButton = new javax.swing.JButton();
        tableScroll = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        separator = new javax.swing.JSeparator();
        personalInformationLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        cellPhoneNumberLabel = new javax.swing.JLabel();
        cellPhoneNumberField = new javax.swing.JTextField();
        directionLabel = new javax.swing.JLabel();
        directionField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        personLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        personLabel.setText("Person");

        personCombo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        personCombo.setModel(personModel);
        personCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personComboActionPerformed(evt);
            }
        });

        insertButton.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        insertButton.setText("Insert Person");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        table.setModel(tableModel);
        ListSelectionListener tableListener = new ListSelectionListener(){
            @Override
            public void valueChanged(ListSelectionEvent e){
                if(e.getValueIsAdjusting()){
                    int rowSelected = table.getSelectedRow();
                    String name = (String) tableModel.getValueAt(rowSelected, 0);
                    String lastName = (String) tableModel.getValueAt(rowSelected, 1);
                    String email = (String) tableModel.getValueAt(rowSelected, 2);
                    String cellphone = (String) tableModel.getValueAt(rowSelected, 3);
                    String direction = (String) tableModel.getValueAt(rowSelected, 4);

                    nameField.setText(name);
                    lastNameField.setText(lastName);
                    emailField.setText(email);
                    cellPhoneNumberField.setText(cellphone);
                    directionField.setText(direction);
                }
            }
        };

        table.getSelectionModel().addListSelectionListener(tableListener);

        tableScroll.setViewportView(table);

        personalInformationLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        personalInformationLabel.setText("Personal Information");

        nameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        nameLabel.setText("Name");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lastNameLabel.setText("Last Name");

        emailLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        emailLabel.setText("Email");

        cellPhoneNumberLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        cellPhoneNumberLabel.setText("Cellphone Number");

        cellPhoneNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cellPhoneNumberFieldActionPerformed(evt);
            }
        });

        directionLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        directionLabel.setText("Direction");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(personalInformationLabel)
                    .addComponent(tableScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(personCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(insertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(personLabel)
                        .addGroup(panelLayout.createSequentialGroup()
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameLabel)
                                .addComponent(emailLabel)
                                .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                                .addComponent(emailField))
                            .addGap(18, 18, 18)
                            .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cellPhoneNumberLabel)
                                .addComponent(lastNameLabel)
                                .addComponent(cellPhoneNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                .addComponent(lastNameField)))
                        .addComponent(directionLabel)
                        .addComponent(directionField))
                    .addComponent(separator))
                .addContainerGap())
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(personLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(insertButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(personCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(personalInformationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(lastNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(cellPhoneNumberLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cellPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(directionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(directionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_personComboActionPerformed

    private void cellPhoneNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cellPhoneNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cellPhoneNumberFieldActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        /* Save the object selected in the combo and casting it into a Person Object*/
        Person personSelected = (Person) personCombo.getSelectedItem();
        
        // creates some variables that will save the person information
        String name = personSelected.getName();
        String lastName = personSelected.getLastName();
        String email = personSelected.getEmail();
        String direction = personSelected.getDirection();
        String cellPhoneNumber = personSelected.getCellPhoneNumber();
        
        //Creates an array that contains the person information together
        String[] personInformation = {name, lastName, email,cellPhoneNumber, direction};
        
        if (peopleInTable.contains(personSelected)){
            JOptionPane.showMessageDialog(null, "That person already exist, please try again");
        } else {
            peopleInTable.add(personSelected);
            tableModel.addRow(personInformation);
        }
        
    }//GEN-LAST:event_insertButtonActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
        
        try {
            // LOOK AND FEEL SETTINGS
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (ClassNotFoundException ex) {
            //Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            //Logger.getLogger(Window.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cellPhoneNumberField;
    private javax.swing.JLabel cellPhoneNumberLabel;
    private javax.swing.JTextField directionField;
    private javax.swing.JLabel directionLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JButton insertButton;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JComboBox<Person> personCombo;
    private javax.swing.JLabel personLabel;
    private javax.swing.JLabel personalInformationLabel;
    private javax.swing.JSeparator separator;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tableScroll;
    // End of variables declaration//GEN-END:variables
}
