/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game.frames;

/**
 *
 * @author MrDoisaac
 */
public class Main extends javax.swing.JFrame {
    private String user1;
    private String user2;
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        user1Rol = new javax.swing.JLabel();
        user2Rol = new javax.swing.JLabel();
        username2Field = new javax.swing.JTextField();
        giftImg = new javax.swing.JLabel();
        username1Field = new javax.swing.JTextField();
        saveUserButton = new javax.swing.JButton();
        playButton = new javax.swing.JButton();
        backgroundImg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(865, 620));
        setResizable(false);

        jPanel1.setLayout(null);

        user1Rol.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(user1Rol);
        user1Rol.setBounds(30, 490, 300, 30);

        user2Rol.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel1.add(user2Rol);
        user2Rol.setBounds(30, 540, 300, 30);

        username2Field.setBackground(new java.awt.Color(255, 255, 255));
        username2Field.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(username2Field);
        username2Field.setBounds(600, 360, 220, 30);

        giftImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tictactoe.gif"))); // NOI18N
        jPanel1.add(giftImg);
        giftImg.setBounds(60, 200, 270, 300);

        username1Field.setBackground(new java.awt.Color(255, 255, 255));
        username1Field.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPanel1.add(username1Field);
        username1Field.setBounds(600, 210, 220, 30);

        saveUserButton.setBackground(new java.awt.Color(207, 216, 228));
        saveUserButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        saveUserButton.setForeground(new java.awt.Color(0, 0, 0));
        saveUserButton.setText("SAVE USERS");
        saveUserButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        saveUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUserButtonActionPerformed(evt);
            }
        });
        jPanel1.add(saveUserButton);
        saveUserButton.setBounds(430, 470, 200, 50);

        playButton.setBackground(new java.awt.Color(207, 216, 228));
        playButton.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        playButton.setForeground(new java.awt.Color(0, 0, 0));
        playButton.setText("LET'S PLAY");
        playButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        playButton.setEnabled(false);
        playButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playButtonActionPerformed(evt);
            }
        });
        jPanel1.add(playButton);
        playButton.setBounds(650, 470, 200, 50);

        backgroundImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backgroundImg.png"))); // NOI18N
        jPanel1.add(backgroundImg);
        backgroundImg.setBounds(0, 0, 870, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        GameFrame game = new GameFrame(user1, user2);
        game.setVisible(true);
        dispose();
    }//GEN-LAST:event_playButtonActionPerformed

    private void saveUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUserButtonActionPerformed
        if(username1Field.getText().isEmpty() || username2Field.getText().isEmpty()){
            user1Rol.setText("Please enter both usernames");
        } else {
            // get both usernames and save them into a variable 
            user1 = username1Field.getText();
            user2 = username2Field.getText();
            // deactives the button "save usernames"
            saveUserButton.setEnabled(false);
            // activates the play button
            playButton.setEnabled(true);
            
            // show the rol for both users
            user1Rol.setText(user1 + " will play first with: X");
            user2Rol.setText(user2 + " will play second with: O");
        }
    }//GEN-LAST:event_saveUserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundImg;
    private javax.swing.JLabel giftImg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton playButton;
    private javax.swing.JButton saveUserButton;
    private javax.swing.JLabel user1Rol;
    private javax.swing.JLabel user2Rol;
    private javax.swing.JTextField username1Field;
    private javax.swing.JTextField username2Field;
    // End of variables declaration//GEN-END:variables
}
