/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package game.frames;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.UIManager;


/**
 *
 * @author MrDoisaac
 */
public class Main extends javax.swing.JFrame {
    // This matrix allows us to know which box is available to click
    private boolean box[][] = new boolean[3][3];
    // First user will be X
    private String turn = "user1";
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        UIManager.put("menuBar.background", Color.RED);
        setSize(600, 600);
        setLocationRelativeTo(null);
        initializeBox();
    }
    
    /**
     * Initialize all the matrix as true, referring that all the box
     * is available to click
     */
    private void initializeBox() {
        for (int i = 0; i < box.length; i++) {
            for (int j = 0; j < box[i].length; j++) {
                box[i][j] = true;
            }
        }
    }
    
    /**
     * Draws an "X" on the button given as an argument
     * @param button The button where the x will be drawn
     */
    private void drawX(JButton button){
        button.setIcon(new ImageIcon(getClass().getResource("/img/x.png")));
    }
    
    /**
     * Draws an "O" on the button given as an argument
     * @param button The button where the "O" will be drawn
     */
    private void drawO (JButton button){
        button.setIcon(new ImageIcon(getClass().getResource("/img/circle.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        panel = new javax.swing.JPanel();
        button00 = new javax.swing.JButton();
        button01 = new javax.swing.JButton();
        button02 = new javax.swing.JButton();
        button10 = new javax.swing.JButton();
        button11 = new javax.swing.JButton();
        button12 = new javax.swing.JButton();
        button20 = new javax.swing.JButton();
        button21 = new javax.swing.JButton();
        button22 = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        gameMenu = new javax.swing.JMenu();
        startAgain = new javax.swing.JMenuItem();
        showResults = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        exit = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel.setLayout(new java.awt.GridLayout(3, 3));

        button00.setBackground(new java.awt.Color(20, 189, 172));
        button00.setOpaque(true);
        button00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button00ActionPerformed(evt);
            }
        });
        panel.add(button00);

        button01.setBackground(new java.awt.Color(20, 189, 172));
        button01.setOpaque(true);
        panel.add(button01);

        button02.setBackground(new java.awt.Color(20, 189, 172));
        button02.setOpaque(true);
        panel.add(button02);

        button10.setBackground(new java.awt.Color(20, 189, 172));
        button10.setOpaque(true);
        panel.add(button10);

        button11.setBackground(new java.awt.Color(20, 189, 172));
        button11.setOpaque(true);
        panel.add(button11);

        button12.setBackground(new java.awt.Color(20, 189, 172));
        button12.setOpaque(true);
        panel.add(button12);

        button20.setBackground(new java.awt.Color(20, 189, 172));
        button20.setOpaque(true);
        panel.add(button20);

        button21.setBackground(new java.awt.Color(20, 189, 172));
        button21.setOpaque(true);
        panel.add(button21);

        button22.setBackground(new java.awt.Color(20, 189, 172));
        button22.setOpaque(true);
        panel.add(button22);

        menuBar.setBackground(new java.awt.Color(51, 51, 51));
        menuBar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuBar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        menuBar.setOpaque(true);

        gameMenu.setBackground(new java.awt.Color(51, 51, 51));
        gameMenu.setText("Game");
        gameMenu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N

        startAgain.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        startAgain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/startAgain.png"))); // NOI18N
        startAgain.setText("Start again");
        gameMenu.add(startAgain);

        showResults.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        showResults.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/results.png"))); // NOI18N
        showResults.setText("Show results");
        gameMenu.add(showResults);
        gameMenu.add(jSeparator1);

        exit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        gameMenu.add(exit);

        menuBar.add(gameMenu);

        helpMenu.setBackground(new java.awt.Color(51, 51, 51));
        helpMenu.setText("Help");
        helpMenu.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // exit button
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void button00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button00ActionPerformed
        if(box[0][0] == true){
            if (turn.equals("user1")){
                drawX(button00);
                turn = "user2";
            }
            else{
                drawO(button00);
                turn = "user1";
            }
            box[0][0] = false;
        }
    }//GEN-LAST:event_button00ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button00;
    private javax.swing.JButton button01;
    private javax.swing.JButton button02;
    private javax.swing.JButton button10;
    private javax.swing.JButton button11;
    private javax.swing.JButton button12;
    private javax.swing.JButton button20;
    private javax.swing.JButton button21;
    private javax.swing.JButton button22;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu gameMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panel;
    private javax.swing.JMenuItem showResults;
    private javax.swing.JMenuItem startAgain;
    // End of variables declaration//GEN-END:variables
}
